### ISSUE TITLE
ros2 bag play --topics option does not work

### ISSUE THREAD

**Issue by janklatte** [ros2/rosbag2#1222]
## Description
I am using ros2 humble and when playing a rosbag with specified topics like shown below:
```
ros2 bag play --topics="/topic1 /topic2" <path/to/rosbag>
```
it opens the database but then exits immediately.

### Expected Behavior
Playback of the entire rosbag but only publishing the specified topics.

### Actual Behavior
Opens the rosbag but then exits and no data is published.

## To Reproduce
record a rosbag with multiple topics and then specify more than one with the `--topics` flag.

## System (please complete the following information)
 - OS: Ubuntu Jammy
 - ROS 2 Distro: Humble
 - Version: ros-humble-rosbag2: 0.15.3-1jammy.20221109.192253

**Comment by emersonknapp** [comment]
I think that due to the quotes, it's trying to select a _single_ topic named `"/topic1 /topic2"` including the spaces as part of the topic name.

Have you tried the following?

```
ros2 bag play /path/to/bag --topics /topic1 /topic2
```

This works for me, whereas I see the behavior you specify when using `--topics="/topic1 /topic2"`.

I'm not entirely certain this is a bug, as this seems like standard commandline behavior - quotes enclose a single argument (which lets you include spaces in that argument) whereas unquoted arguments are space-delimited. Maybe one thing that could make this clearer is if we said `No topic found with name "/topic1 /topic2"` warning message. However, this wouldn't catch this same error applied to, say, `--regex` topic filtering.

**Comment by janklatte** [comment]
My bad this works for me now as well. I thought I tried the --topics /topic1 /topic2 option as well with the same behavior but must have done something wrong.

**Comment by AswinkarthikeyenAK** [comment]
Hi, 
How do you do the same while recording ros bag file? I would like to exclude multiple topics. 
Say there are 4 topic, I want to record all and exclude topic1 and topic3

eg: ros2 bag record -s mcap --all --exclude /topic1
this excludes topic 1, 

however, 
eg: ros2 bag record -s mcap --all --exclude /topic1 /topic3
gives following error, [ERROR] [ros2bag]: Must specify only one option out of topics, --regex or --all

Using ros humble

Thanks

**Comment by MichaelOrlov** [comment]
@AswinkarthikeyenAK See answer here https://github.com/ros2/rosbag2/issues/1263#issuecomment-1471390312
