### ISSUE TITLE
[WARN] [rosbag2_storage]: No storage plugin found with id 'sqlite3'.

### ISSUE THREAD

**Issue by lonebots** [ros2/rosbag2#1235]
When I was trying to play a bag file recorded with `ros2 bag record` command I got this warning, 

```bash
ros2 bag play hardware_status/
[WARN] [1674566449.406779601] [rosbag2_storage]: No storage plugin found with id 'sqlite3'.
[INFO] [1674566449.407724645] [rosbag2_storage]: Opened database 'hardware_status/hardware_status_0.db3' for READ_ONLY.
[INFO] [1674566449.407748123] [rosbag2_player]: Set rate to 1
[INFO] [1674566449.410152908] [rosbag2_player]: Adding keyboard callbacks.
[INFO] [1674566449.410169945] [rosbag2_player]: Press SPACE for Pause/Resume
[INFO] [1674566449.410177942] [rosbag2_player]: Press CURSOR_RIGHT for Play Next Message
[INFO] [1674566449.410184624] [rosbag2_player]: Press CURSOR_UP for Increase Rate 10%
[INFO] [1674566449.410190836] [rosbag2_player]: Press CURSOR_DOWN for Decrease Rate 10%
[WARN] [1674566449.410236544] [rosbag2_storage]: No storage plugin found with id 'sqlite3'.
[INFO] [1674566449.410330423] [rosbag2_storage]: Opened database 'hardware_status/hardware_status_0.db3' for READ_ONLY.
```

### Additional information 

1. OS : Ubuntu 22.04 LTS
2. ROS2 distro : Humble Hawksbill

**Comment by emersonknapp** [comment]
Summary of investigation:
* This was fixed in Humble in https://github.com/ros2/rosbag2/pull/1219 (on December 21 2022)
* I do see that there's been a version bump (to 0.15.4) on Humble since then https://github.com/ros2/rosbag2/pull/1231.
* The package was bloom released, it shows 0.15.4: https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L4980
* ROS Index still shows 0.15.3:  https://index.ros.org/p/rosbag2/github-ros2-rosbag2/#humble 
* It appears there was a Humble sync 12/16 but not one since then (we're probably about due): https://discourse.ros.org/c/release/humble/73

So, the fix is all in, and should actually go through the build pipelines to binary packages "soon" (apt syncs are not on a hard schedule but happen approximately every 4-8 weeks)

I'm inclined to close this as fixed, please reopen if it doesn't seem that way to you.
