### ISSUE TITLE
Messages published before /clock recorded with timestamp 0 (--use-sim-time) 

### ISSUE THREAD

**Issue by adamkrawczyk** [ros2/rosbag2#1276]
## Description

When recording the data with `--use-sim-time` the messages published before the `/clock` are recorded with timestamp 0 this results in false statistics and so on. See the graph from rqt_graph 
![image](https://user-images.githubusercontent.com/29305346/231087260-14a20b98-f14d-4ad5-a6aa-a8b4b92be2c4.png)

## Related Issues

-

## Completion Criteria

Data recording with consecutive timestamps

## Implementation Notes / Suggestions

Add the option to ignore or some buffer or restamp. I don't know if the behavior is expected or not, please share your thoughts. This issue is more like a question than a Feature request

## Testing Notes / Suggestions

1. pub to `/clock` 
2. pause publishing
3. begin record some other topics and resume publishing time

**Comment by emersonknapp** [comment]
This is a reasonable complaint and I'm not sure what the best solution is here, either. The 0->first-clock gap would make playback behavior unreasonable.

More context on current functionality: `use_sim_time` is a generic parameter to nodes, which is set on the `Recorder` node so that its `this->get_clock()->now()` returns the result of the `/clock` topic. So, the current behavior is a result of `rclcpp` behavior. If we decide to mitigate this  somehow, we could decide that `0` is a special time value that means "unset" and detect that to do whatever it is that we do.

Notes on suggested resolutions:
* "ignore" - maybe we add a `--wait-for-clock` option and don't record any messages until a clock value  is received. Definitely simplest option
* "buffer" - if we  were to do this, we would need a max buffer size, and then I guess stamp all buffered messages with the first-received clock value?
* "restamp" - this one is probably infeasible, mcap storage format is append-only

**Comment by adamkrawczyk** [comment]
Thanks for the answer @emersonknapp, 

The `--wait-for-clock` seems to be a good solution. Currently, we have resolved this with option `--start-paused` and beginning recording manually.  I wonder if this `wait-for-clock` should be the default, and if the user wants to could use `--record-without-clock` (not sure about the name).

**Comment by MichaelOrlov** [comment]
I would hardcode this  `--wait-for-clock` behavior by default for the cases when `--use_sim_time` parameter uses.
It will be too much to have extra optional parameter for optional `--use_sim_time` parameter.
I don't imagine a case when using `--use_sim_time` and not waiting for the clock will be useful.

**Comment by Grisly00** [comment]
This sounds like it is related to my issue #1256 where I have the problem that recorded bag files sometimes start at `nanoseconds_since_epoch: 0` and can't be played. Looking forward to a fix!

Edit: @adamkrawczyk Also `--start-paused` does not seem to solve this consistently for me. I also played around with reliable QoS profiles for `/clock`, but it seems to be more or less random if the recorded bag file has the correct start time or starts at `0`. Worst part though at the moment is that I couldn't figure out a way to find out if it is working or not while recording, meaning I can only check afterwards which is pretty time consuming when converting hour long bag files. Maybe you have some tips for me.
