### ISSUE TITLE
Test the type in the system and the type in used for generate the msg in the bag are the same

### ISSUE THREAD

**Issue by luccosta** [ros2/rosbag2#1495]
## Description

If you recorded a bag with a old version of a message type and try to play it in a environment with a new version it will just not be published. This way, is better to throw some warn about this mistake.

## Completion Criteria

- Detect that a bag is holding a message with a type different than the sourced in the current system using something like [this](https://github.com/ros2/ros2/issues/1159).
- Throw a warn.

**Comment by MichaelOrlov** [comment]
@luccosta In rosbag2 player we don't do any checks about data type since we are publishing messages directly in already serialized form and we don't need to care about type at all.
See
https://github.com/ros2/rosbag2/blob/d6030c4c26443c87a094c3091c3cd2059da3816d/rosbag2_transport/src/rosbag2_transport/player.cpp#L216-L234
We are doing our best effort on the rosbag2 side. In your scenario, the messages were likely lost on the receiver side or somewhere on the transport layer.  
I have examples in my practice when messages stored with old message definitions were successfully published by the rosbag2 player with the new message definition. The correctness of such operation is another question. 
We will handle it more correctly when a relative part of the REP2011/REP2016 will be implemented on the RCLCPP player.
