### ISSUE TITLE
Pause/resume `ros2 bag play` with keyboard controls

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rosbag2#55]
# Description

Like in ROS 1, there should be a chance to control the replaying of a bag file.

`spacebar` should toggle the start/pause replaying.
`s` should solely spin the bag once.

Generally, as for now, there is no status feedback given when replaying a bag file. As a first step, there should be a message printed, whether the bag file is currently publishing data or not.

## Completion criteria

* [ ] `ros2 bag play` uses `keyboard_handler` to receive key callbacks
* [ ] `spacebar` toggles pause/resume state for playback
* [ ] `s` does `play_next`
* [ ] `ros2 bag play` prints a help message when playback starts, explaining these controls

## Related issues

#696 

## Implementation Notes

* May need to bloom-release `keyboard_handler` into Rolling - it is not yet in use.
* May need to expose keybindings to Python layer via Pybind - it makes sense for the CLI to define which keys do what, rather than hardcoding on the C++ end

## Testing Notes

* May be difficult to do key-based end-to-end testing. It should be OK to mock the key callbacks

**Comment by weihunko** [comment]
Hi @Karsten1987 , while troubleshooting some perception issues with the recorded bag file, we would hope to have the functionalities to go back and forward a fixed amount of time, maybe 100ms or 1 second. 

For forwarding one step, we can use the `spin_once` function, but is it possible to go back one step or a fix amount of time?

**Comment by Karsten1987** [comment]
I don't think I would temper with the `spin_once` functionality for going back and forth, more like with the "current" time step. 
See https://github.com/ros2/rosbag2/blob/56e440caca4bed3ea4cdde795a24a1bc60cdc355/rosbag2_transport/src/rosbag2_transport/player.cpp#L160

I imagine the overall behavior being the same, whether you'd like to step forward or backward. You'd simply add a `delta` to the current time and let the bag file play as usual.
Regardless of how you'd realize this though, there's the [issue of time (simulated) time](https://github.com/ros2/rosbag2/issues/99), which comes into play here as well, I assume.

**Comment by weihunko** [comment]
@Karsten1987 From 
https://github.com/ros2/rosbag2/blob/56e440caca4bed3ea4cdde795a24a1bc60cdc355/rosbag2_transport/src/rosbag2_transport/player.cpp#L160

 It looks like `start_time_` is only used to control the publishing rate? Does it also used to determine which messages to publish according to their timestamps?

**Comment by Kaju-Bubanja** [comment]
What's the status of this issue? Pausing rosbags was working fine in ros, does this feature not exists in ros2?

**Comment by emersonknapp** [comment]
Not yet - it's still an open feature request

**Comment by MichaelOrlov** [comment]
@emersonknapp @Karsten1987 I've implemented this new API aka `play`, `pause` and `play next in pause` in Apex.AI. \
We want to upstream our changes.  \
Could you please assign this issue to me?

**Comment by emersonknapp** [comment]
Two slightly different approaches to this feature are being introduced by 
https://github.com/ros2/rosbag2/pull/675 - design for sim-time handling allows for pause/resume time
https://github.com/ros2/rosbag2/pull/666 - starting and stopping playback (but not time) by lifecycle node

We'd be happy to consider your approach as well, if you open a PR for it. Note that we prefer to review small incremental changes, as they are easier to review and validate.

**Comment by MichaelOrlov** [comment]
Hi @emersonknapp Thank you for pointing out about other approaches. \
I am in the process of upstreaming my version to the branch to be able to create pull request. It turns out that our fork of the rosbag2 slightly different and it's not straight forward to cherry pick commits, I have to address changes manually and some time re-implement them to accommodate difference in base.  

As regards to the complexity and size of the delta. This feature looks simple, like add new API with a few methods, but it turns out this is not trivial in implementation. If want to replay deterministically in time domain with pause/resume and possibility to change speed and play next in pause. \
It's kind of challenging to implement and handling corner cases especially keep desired time interval between  messages after resuming with changed speed after played a few messages with play-next API. Also it was a quite challenging to implement it efficiently without locking mutexes in runtime and without affecting performance and avoiding race conditions and undefined behaviors. Also one important moment I was keeping in mind when implementing this feature is that errors in time delay (due to the some overhead) shouldn't  accumulate in sequence of playing messages and should be local for one inter-message interval. 

My approach probably more straight forward and simple in design rather than a couple previous ones but still a little bit complicated in understanding in some cases.

**Comment by MichaelOrlov** [comment]
Hi @emersonknapp @Karsten1987 I've created [Pull request](https://github.com/ros2/rosbag2/pull/680). Could you please kindly review it?
