### ISSUE TITLE
Compression and playback rate options for Dashing

### ISSUE THREAD

**Issue by charlielito** [ros2/rosbag2#562]
## Description

Is it possible to add the compression and playback with rate options for dashing? As far I could see these are only in master and Foxy. Any reasons?

**Comment by emersonknapp** [comment]
Generally we don't release new major features into old distributions - these ones especially would be fairly difficult as they touch many parts of the codebase and are  hard to separate from other changes that have happened since Dashing. 

Given the difficulty, new APIs, and short lifespan of Dashing (May 2021) - I don't expect that this will happen.
