### ISSUE TITLE
colcon build failed on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by SandyWare** [ros2/rosbag2#736]
## Description
1. First I have successfully install ROS2 crystal from the source.
`rosdep install --from-paths src --ignore-src --rosdistro crystal -y --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 rti-connext-dds-5.3.1 urdfdom_headers"`

  and then build ROS2 Crystal code....
        `colcon build --symlink-install`
2. Then I have Clone ROSBag2 from the **crystal branch**.
`    $ git clone -b crystal** https://github.com/ros2/rosbag2.git
`
3. When I try to build ROSBag2
`  $colcon build --cmake-clean-first --merge-install`  
     
**It gives me below error logs:**
	Finished <<< rosbag2_test_common [38.4s]
	Starting >>> rosbag2_storage
	--- stderr: sqlite3_vendor
	make[1]: *** No rule to make target 'clean'.  Stop.
	make: *** [clean] Error 2

4. Then using python3 below code I try to load ROSBag2
```
	import rosbag
	bag = rosbag.Bag('51_57_Rellis_Campus_Parking_lot+road.bag')
```
   **It give me below error :**
	ros2 bag info 51_57_Rellis_Campus_Parking_lot+road.bag
	DISCLAIMER
	ros2 bag is currently under development and not ready to use yet
	[ERROR] [rosbag2_storage]: Failed to load metadata: Exception on parsing info file: bad file
	[ERROR] [rosbag2_storage]: Could not open '51_57_Rellis_Campus_Parking_lot+road.bag' with 'sqlite3'. Error: Failed to read from bag '51_57_Rellis_Campus_Parking_lot+road.bag': No metadata found.
	[ERROR] [rosbag2_storage]: Could not load/open plugin with storage id 'sqlite3'.
	[ERROR] [rosbag2_transport]: Could not read metadata for 51_57_Rellis_Campus_Parking_lot+road.bag. Please specify the path to the folder containing an existing 'metadata.yaml' file or provide correct storage id if metadata file doesn't exist (see help).
	
## System (please complete the following information)
 - OS: Ubuntu Bionic (Ubuntu 18.04.5 LTS)
 - ROS 2 Distro: crystal
 - Version:  branch crystal
 - Compiler : Python 3.6.9 and gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 
 - ROS2 : crystal

## Additional context
  I already tried with deb pcakges, but it don't work for me.
  https://github.com/ros2/rosbag2/issues/733
  My task is to load ROS Bags using ROSBag2. 
  
Your suggestions or help are greatly appreciated.

**Comment by emersonknapp** [comment]
In order to read ROS 1 bags - you need the package [`rosbag2_bag_v2`](https://github.com/ros2/rosbag2_bag_v2) (`bag_v2` is the storage format of ROS 1 bags). The default `rosbag2` installation only comes with the SQlite storage backend, which is the default  for ROS 2 bags.

The package for this would look like `ros-crystal-rosbag2-bag-v2-plugins`. Though since you're using an EOL distro (Crystal), are binaries still available for you? Regardless, you may be able to build that package from source as well, for your ROS 1 -> ROS 2 bag conversions.

This question is more of a general usage question and would be better suited to answers.ros.org - I suggest you post there, and I will close this issue, as GitHub is intended to track specific bugs and new features.
