### ISSUE TITLE
Notification of significant events during bag recording and playback

### ISSUE THREAD

**Issue by gbiggs** [ros2/rosbag2#884]
## Description

During bag recording and playback, there are events that occur in which the user may be interested. For example, the user may wish to know when a split in the output bag file has occurred during recording, or when a new split has been opened during playback, or when a new topic has been added to a bag file.

Motivating use case:

Automatic archiving of large bag files during recording. When recording a very large bag, with multiple splits, disc space restrictions or transfer time restrictions may mean that the user wishes to move or copy finished splits too another location _while recording is still ongoing_. This requires knowing when a split has occurred and thus another split file is ready for transfer. This notification should be available via a topic, to support use by an external tool, as well as programmatically via a callback, to support the user creating an integrated record-and-archive tool.

## Related Issues

None.

## Completion Criteria

- rosbag2 shall have a list of known events that the use can receive notifications about.
- When an event occurs, rosbag2 shall broadcast that event and any relevant information.
- rosbag2 shall allow a user to register their interest in receiving notifications about an event.
- rosbag2 shall have a mechanism for a user to receive notifications about an event in a separate tool from the recording tool.
- rosbag2 shall have a mechanism for a user to receive notifications programmatically about an event.

## Implementation Notes / Suggestions

I have produced a very (very) simple proof of concept that provides callback- and topic-based notifications whenever the output bag is split during recording. [You can see it here](https://github.com/ros2/rosbag2/compare/galactic...gbiggs:gbiggs/bag-events-prototype). Note that it doesn't come with unit tests, so to test it you will need to start up a recorder with a low maximum bag size to cause rapid splitting. Then subscribe to the output topic `/bag_events`, and, assuming I haven't broken anything, you should receive an `example_interfaces/msg/Empty` message each time a split occurs.

The prototype implementation adds

- an interface to writers for registering callbacks to be called when,
- an `enum` for specifying callback types (only one type is specified, for output split events),
- a method that calls all callbacks that match a specified callback type, which is called when a split occurs, and
- a topic published by the recorder that uses a callback to publish a message when a split occurs.

I think this general structure of callbacks in `rosbag2_cpp`, and building on those to provide topic-based notification in `rosbag2_transport`, works well. It satisfies both the requirement for programmatic notification by those who are building rosbag2 functionality into their own tool or node, and the requirement for external notification for those building separate tools.

To be discussed:

1. What is the ideal architecture for event notification?
2. What events should be notified?
3. What information should accompany each event?
4. Should all events use the same callback declaration (i.e. a universal callback that receives an `enum` or similar identifying the event type and a universal information struct) or should we use a more complex callback system similar to the QoS callbacks of subscribers (each event type has its own callback type with its own information structure)?
5. In line with the above, what message(s) should we define for event notification?
6. Can this functionality be added to the Galactic release of rosbag2 or will we need to change API/ABI and thus limit it to Rolling/Humble?

## Testing Notes / Suggestions

Each event will need its own tests. Both callback notification and topic notification will need to be tested. Callback notifications can be tested in the `rosbag2_cpp` tests, but topic notification will potentially require a full integration test.

For the split-during-recording requirement, the test should use a mock storage that "splits" after just a few messages.

**Comment by aditya2592** [comment]
Hi, this is a very useful feature! Thanks for adding it! I was wondering if an event should also be published when the final bag file has been closed. Currently this is not notified since publish happens only a split is created. I wanted to raise a PR for this, does it make sense to publish to existing `events/write_split` or should this be published on a new topic?

**Comment by MichaelOrlov** [comment]
Hi, @aditya2592 I have just was thinking about the same today.  
From one hand I would expect to get notification on the same topic for the reasons that in most cases receiver of such events is some sort of post processing node which could compress bag which has been finished and start sending it to the cloud in the background. And it will be much easier to organize logic for such node if it would be just one subscription.
Although from another hand using `events/write_split` to notify about closing last bag might looks a bit confusing.

I tend to incline to agree that closing last bag is sort of equal to call split in this case. Parameter `bag_split_info_.opened_file` could be an empty string to indicate that it was the last file and that it was actually close rather than split.

Could you please provide more details for what use cases or scenario you are going to use notification about closing the last file?

**Comment by aditya2592** [comment]
Hi @MichaelOrlov. Thanks for the fast reply. The use case is to upload them to cloud as you correctly predicted and hence I was also inclined to publish to the same topic.

**Comment by aditya2592** [comment]
@MichaelOrlov, I made a draft PR for publishing a split event on bag close [here](https://github.com/ros2/rosbag2/pull/1213/files). One issue I ran into: bags get closed through C++ destructors and there is no API to close it. As a result if I add event publishing in the destructor it doesn't actually get published because the ros2 context is probably getting destroyed. To overcome this, I added various `close` functions that close the bag through an API and also publish and event. Please let me know what you think of this approach.

**Comment by MichaelOrlov** [comment]
Hi @aditya2592, Adding "close" methods is Ok.  
Although where from will be called "recorder::close()"?  
I am afraid that this feature with notification of closing latest file doesn't fit in current design of the recorder.
Indeed we are finishing recording by handling `CTRL+C` at which we are calling `rclcpp::shutdown();` 
The problem is that even calling `recorder::close()` before `rclcpp::shutdown();` in signal handler is not easy task.
Also we might need to cancel executor "exec_->cancel()" first and add triggering recorder in pause mode before closing writer to avoid calling `writer->write()` from subscriptions callback when writer has been already closed.
You can give it a try with all precautions which I listed above.

**Comment by MichaelOrlov** [comment]
Hi @aditya2592, I pushed a couple commits on your branch trying to gracefully handle `SIGTERM` and call Recorder::stop() from signal handler. Please take a look on my suggestion https://github.com/ros2/rosbag2/pull/1213/commits.
