### ISSUE TITLE
Header files are missing in the include folder

### ISSUE THREAD

**Issue by bednarhonza** [ros2/rosbag2#965]
## Description
`#include <rosbag2_transport/qos.hpp>` does not work, because `qos.hpp` file is missing in the `/opt/ros/galactic/include/rosbag2_transport/ folder.

## To Reproduce
1. Write a code that includes `#include <rosbag2_transport/qos.hpp>`.
2. Using the default packages, it will not compile since the file is not there.

## System (please complete the following information)
 - OS: Ubuntu 20.04
 - ROS 2 Distro: Galactic
 - Version: 0.9.1 - installed through .deb packages. I tried to compile the newest version for galactic and the problem was the same.

**Comment by clalancette** [comment]
> Is there another method how to do it?

No, but it shouldn't be necessary.  Since that header isn't available in Galactic, the build of plotjuggler shouldn't need it.  This seems like a bug in plotjuggler, or at the very least it needs a backport of some things to Galactic from Rolling.

Regardless, I think this particular issue is solved, so I'll close this out.
